openapi: 3.0.3
info:
  title: AIS Reporter API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    [pdjr-ais-reporter](https://github.com/pdjr-signalk/pdjr-ais-reporter)
    is a plugin for the
    [Signal K node server](https://github.com/SignalK/signalk-server).

    A Signal K server hosting the plugin will present this API under
    the root https://*server_ip*:*server_port*/plugins/interfacewatchdog.
externalDocs:
  description: Plugin README document
  url: https://github.com/pdjr-signalk/pdjr-ais-reporter#readme 
paths:
  /status:
    get:
      description: |
        Get a digest reporting the status of all configured endpoints.
      responses:
        200:
          description: |
            Success.
            The response body is an object containing a status report
            object for each endpoint keyed by endpoint name.
          content:
            application/json:
              schema:
                type: object
                properties:
                  endpoint:
                    type: object
                    properties:
                      ipAddress:
                        description: IP address of the report endpoint.
                        type: string
                        example: 192.168.1.12
                      port:
                        description: Port number of the report endpoint.
                        type: number
                        example: 12345
                      lastTransmission:
                        description: UTC date of the most recent report transmission.
                        type: string
                        example: Fri, 06 Dec 2024 11:09:46 GMT
                      totalNumberOfPositionReports:
                        description: Count of the total number of position reports sent to this endpoint this session.
                        type: number
                        example: 134
                      totalNumberOfStaticDataReports:
                        description: Count of the total number of static data reports sent to this endpoint this session.
                        type: number
                        example: 11
        500:
          description: |
            Error.
            The server was unable to service the request.       
